CREATE TABLE [dbo].[fiscal_calendar] (
    [date_key]                  INT          NOT NULL,
    [fiscal_day_of_period]      INT          NULL,
    [fiscal_day_of_quarter]     INT          NULL,
    [fiscal_day_of_year]        INT          NULL,
    [fiscal_period_key]         INT          NULL,
    [fiscal_period_start_date]    DATE         NULL,
    [fiscal_period_end_date]      DATE         NULL,
    [fiscal_period_of_quarter]  INT          NULL,
    [fiscal_period_of_year]     INT          NULL,
    [fiscal_period_desc_01]     VARCHAR (20) NULL,
    [fiscal_period_desc_02]     VARCHAR (20) NULL,
    [fiscal_period_desc_03]     VARCHAR (20) NULL,
    [fiscal_period_desc_04]     VARCHAR (20) NULL,
    [fiscal_period_day_count]      INT          NULL,
    [fiscal_period_weekday_count]  INT          NULL,
    [fiscal_period_closed_ind] BIT NULL,
    [fiscal_quarter_key]        INT          NULL,
    [fiscal_quarter_start_date]   DATE         NULL,
    [fiscal_quarter_end_date]     DATE         NULL,
    [fiscal_quarter_of_year]    INT          NULL,
    [fiscal_quarter_desc_01]    VARCHAR (20) NULL,
    [fiscal_quarter_desc_02]    VARCHAR (20) NULL,
    [fiscal_quarter_desc_03]    VARCHAR (50) NULL,
    [fiscal_quarter_desc_04]    VARCHAR (50) NULL,
    [fiscal_quarter_period_count]  INT          NULL,
    [fiscal_quarter_day_count]     INT          NULL,
    [fiscal_quarter_weekday_count] INT          NULL,
    [fiscal_year_key]           INT          NULL,
    [fiscal_year]               INT          NULL,
    [fiscal_year_start_date]      DATE         NULL,
    [fiscal_year_end_date]        DATE         NULL,
    [fiscal_year_desc_01]       VARCHAR (20) NULL,
    [fiscal_year_period_count]     INT          NULL,
    [fiscal_year_quarter_count]    INT          NULL,
    [fiscal_year_day_count]        INT          NULL,
    [fiscal_year_weekday_count]    INT          NULL,
    [fiscal_year_closed_ind] BIT NULL,
    fiscal_week_index INT NULL,
    fiscal_period_index INT NULL,
    fiscal_quarter_index INT NULL,
    fiscal_year_index INT NULL,
    CONSTRAINT dbo_fiscal_calendar_pk PRIMARY KEY (date_key)
);

