CREATE TABLE [dbo].[gl_tran] (
    [gl_tran_key]                INT           NOT NULL,
    [client_key]                 INT           NOT NULL,
    [project_key]                INT           NOT NULL,
    [operating_group_key]        INT           NOT NULL,
    [resource_key]               INT           NOT NULL,
    [gl_tran_date_key]           INT           NOT NULL,
    [net_amt]                    MONEY         NOT NULL,
    [income_amt]                 MONEY         NULL,
    [expense_amt]                MONEY         NULL,
    [other_income_expense_amt]   MONEY         NULL,
    [expense_overhead_amt]       MONEY         NULL,
    [net_expense_cogs_amt]       MONEY         NULL,
    [net_expense_amt]            MONEY         NULL,
    [net_revenue_amt]            MONEY         NULL,
    [cogs_amt]                   MONEY         NULL,
    [net_cogs_amt]               MONEY         NULL,
    [reimb_expense_income_amt]   MONEY         NULL,
    [reimb_expense_cost_amt]     MONEY         NULL,
    [employee_cogs_amt]          MONEY         NULL,
    [contractor_cogs_amt]        MONEY         NULL,
    [w2t_cogs_amt]               MONEY         NULL,
    [employee_cost_amt]          MONEY         NULL,
    [contractor_cost_amt]        MONEY         NULL,
    [w2t_cost_amt]               MONEY         NULL,
    [gross_profit_amt]           MONEY         NULL,
    [non_cogs_amt]               MONEY         NULL,
    [net_profit_amt]             MONEY         NULL,
    [centric_cost_amt]           MONEY         NULL,
    [centric_cost_transfer_amt]  MONEY         NULL,
    [net_centric_cost_amt]       MONEY         NULL,
    [bu_cost_amt]                MONEY         NULL,
    [operating_profit_amt]       MONEY         NULL,
    [shared_profit_transfer_amt] MONEY         NULL,
    [gl_tran_dt]                 DATE          NOT NULL,
    [gl_tran_type]               VARCHAR (100) NULL,
    [gl_category]                VARCHAR (100) NULL,
    [gl_account]                 VARCHAR (100) NULL,
    [gl_subaccount]              VARCHAR (100) NULL,
    [gl_rollup_account]          VARCHAR (250) NULL,
    [gl_forecast_rollup_account] VARCHAR (250) NULL,
	[memo] VARCHAR(4000) NULL,
    [source_key]                 INT           NOT NULL,
    [source_revision_dtm]        DATETIME      NOT NULL,
    [source_revision_actor]      VARCHAR (200) NULL,
    [init_process_batch_key]     INT           NOT NULL,
    [process_batch_key]          INT           NOT NULL,
    CONSTRAINT [gl_tran_pk] PRIMARY KEY CLUSTERED ([gl_tran_key] ASC)
);

